### ISSUE TITLE
Settings aren't working

### ISSUE THREAD

**Issue by SabeDoesThings** [lwz7512/love2d-made-easy#8]
So I updated my vscode and for some reason my settings weren't enabled. I restarted vscode, restarted my computer, and it did not work the only setting I had on was the launch button and that was not showing up I even turned it off and back on and it still wasn't working idk why. Please help if this isn't fixed I wont be able to run love.
![Screenshot 2023-03-30 155610](https://user-images.githubusercontent.com/122580233/228962691-755d0c4f-4771-4e25-9021-fed834660c11.png)

**Comment by SomewhatMay** [comment]
Hey, how did u fix this? I'm having the same issue.

**Comment by SabeDoesThings** [comment]
@SomewhatMay hey if you are still having the issue I right clicked on the love2d icon and it shows you want to disable.
![Screenshot 2023-07-05 174354](https://github.com/lwz7512/love2d-made-easy/assets/122580233/3e753e24-f23a-48ce-b5b6-d4cd6e262edc)
