### ISSUE TITLE
No launch button displayed

### ISSUE THREAD

**Issue by romevidal** [lwz7512/love2d-made-easy#9]
I just installed the extension and it's not displaying the launch button. It's not much of a dealbreaker because I set shortcut keys (Shift+Alt+L) to launch it anyway, but it was something I noticed was missing.

![image_2023-08-17_153906135](https://github.com/lwz7512/love2d-made-easy/assets/115720194/92ca12cd-5ece-49bf-a981-e5c4a100cc43)

**Comment by romevidal** [comment]
I figured it out. I've got a long list of options that were hidden under "More Actions..." and only 8 can fit on screen at a time. I just had to set the less commonly used actions to hide by right-clicking "More Actions...".

**Comment by lwz7512** [comment]
latest version 1.10.2 have removed unnecessary actions from action list, just keep the `run`  action to enable the launch button appear on the editor, you may want to make an update! 
thank you for patience!
